package avahi

// #cgo pkg-config: avahi-client
// #include "glue.h"
import "C"

const (
	DNS_CLASS_IN                    = C.AVAHI_DNS_CLASS_IN
	DNS_TYPE_A                      = C.AVAHI_DNS_TYPE_A
	DNS_TYPE_AAAA                   = C.AVAHI_DNS_TYPE_AAAA
	DNS_TYPE_CNAME                  = C.AVAHI_DNS_TYPE_CNAME
	DNS_TYPE_HINFO                  = C.AVAHI_DNS_TYPE_HINFO
	DNS_TYPE_MX                     = C.AVAHI_DNS_TYPE_MX
	DNS_TYPE_NS                     = C.AVAHI_DNS_TYPE_NS
	DNS_TYPE_PTR                    = C.AVAHI_DNS_TYPE_PTR
	DNS_TYPE_SOA                    = C.AVAHI_DNS_TYPE_SOA
	DNS_TYPE_SRV                    = C.AVAHI_DNS_TYPE_SRV
	DNS_TYPE_TXT                    = C.AVAHI_DNS_TYPE_TXT
	DOMAIN_BROWSER_BROWSE           = C.AVAHI_DOMAIN_BROWSER_BROWSE
	DOMAIN_BROWSER_BROWSE_DEFAULT   = C.AVAHI_DOMAIN_BROWSER_BROWSE_DEFAULT
	DOMAIN_BROWSER_BROWSE_LEGACY    = C.AVAHI_DOMAIN_BROWSER_BROWSE_LEGACY
	DOMAIN_BROWSER_MAX              = C.AVAHI_DOMAIN_BROWSER_MAX
	DOMAIN_BROWSER_REGISTER         = C.AVAHI_DOMAIN_BROWSER_REGISTER
	DOMAIN_BROWSER_REGISTER_DEFAULT = C.AVAHI_DOMAIN_BROWSER_REGISTER_DEFAULT
	ENTRY_GROUP_COLLISION           = C.AVAHI_ENTRY_GROUP_COLLISION
	ENTRY_GROUP_ESTABLISHED         = C.AVAHI_ENTRY_GROUP_ESTABLISHED
	ENTRY_GROUP_FAILURE             = C.AVAHI_ENTRY_GROUP_FAILURE
	ENTRY_GROUP_REGISTERING         = C.AVAHI_ENTRY_GROUP_REGISTERING
	ENTRY_GROUP_UNCOMMITED          = C.AVAHI_ENTRY_GROUP_UNCOMMITED

	LOOKUP_NO_ADDRESS       = C.AVAHI_LOOKUP_NO_ADDRESS
	LOOKUP_NO_TXT           = C.AVAHI_LOOKUP_NO_TXT
	LOOKUP_RESULT_CACHED    = C.AVAHI_LOOKUP_RESULT_CACHED
	LOOKUP_RESULT_LOCAL     = C.AVAHI_LOOKUP_RESULT_LOCAL
	LOOKUP_RESULT_MULTICAST = C.AVAHI_LOOKUP_RESULT_MULTICAST
	LOOKUP_RESULT_OUR_OWN   = C.AVAHI_LOOKUP_RESULT_OUR_OWN
	LOOKUP_RESULT_STATIC    = C.AVAHI_LOOKUP_RESULT_STATIC
	LOOKUP_RESULT_WIDE_AREA = C.AVAHI_LOOKUP_RESULT_WIDE_AREA

	PUBLISH_ALLOW_MULTIPLE = C.AVAHI_PUBLISH_ALLOW_MULTIPLE
	PUBLISH_NO_ANNOUNCE    = C.AVAHI_PUBLISH_NO_ANNOUNCE
	PUBLISH_NO_PROBE       = C.AVAHI_PUBLISH_NO_PROBE
	PUBLISH_UNIQUE         = C.AVAHI_PUBLISH_UNIQUE
	PUBLISH_UPDAT          = C.AVAHI_PUBLISH_UPDATE
	RESOLVER_FAILURE       = C.AVAHI_RESOLVER_FAILURE
	RESOLVER_FOUND         = C.AVAHI_RESOLVER_FOUND
	SERVER_COLLISION       = C.AVAHI_SERVER_COLLISION
	SERVER_FAILURE         = C.AVAHI_SERVER_FAILURE
	SERVER_INVALID         = C.AVAHI_SERVER_INVALID
	SERVER_REGISTERING     = C.AVAHI_SERVER_REGISTERING
	SERVER_RUNNING         = C.AVAHI_SERVER_RUNNING
	WATCH_ERR              = C.AVAHI_WATCH_ERR
	WATCH_HUP              = C.AVAHI_WATCH_HUP
	WATCH_IN               = C.AVAHI_WATCH_IN
	WATCH_OUT              = C.AVAHI_WATCH_OUT
)
